spring:
  application:
    name: unique-id-generator
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
      host: 127.0.0.1
      port: 8500

hot-cache:
  max-size: 1000000

snowflake:
  node-id-bits: 10
  sequence-bits: 12
  custom-epoch: 1577836800000 #01.01.2020 00:00:00